# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5W2_ZjA6lkedJ3yHpkgjK0cB4SHmbMF
"""

# =============================================================================
# COMPREHENSIVE NLP PIPELINE FOR TRAFFIC VIOLATION CLASSIFICATION
# =============================================================================

import pandas as pd
import numpy as np
import re
import string
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

print("🚀 COMPREHENSIVE NLP PIPELINE FOR TRAFFIC VIOLATION ANALYSIS")
print("=" * 70)

# Set random seeds for reproducibility
np.random.seed(42)

# =============================================================================
# 1. CREATE COMPREHENSIVE TRAFFIC VIOLATION DATASET
# =============================================================================

def create_comprehensive_dataset():
    """Create a comprehensive traffic violation dataset with enough examples for stratified split."""

    violation_data = {
        'text': [
            "Driver was not wearing helmet while riding motorcycle on MG Road",
            "Vehicle exceeded speed limit by 40 kmph on national highway",
            "Car jumped red signal at Benz Circle intersection during peak hours",
            "Motorcycle with three passengers triple riding violation",
            "Driver using mobile phone while driving vehicle in city area",
            "Truck parked in no parking zone near bus stand causing traffic jam",
            "Vehicle driving wrong side on one way street creating danger",
            "Drunk driving detected during night patrol with breath analyzer",
            "No valid insurance documents presented during police checking",
            "Pollution under control certificate expired for the vehicle",
            "Heavy vehicle overloading with construction material beyond limit",
            "License not carried by driver during traffic police inspection",
            "Seat belt not worn by driver and front seat passenger in car",
            "Illegal modification of vehicle exhaust system creating noise",
            "Oversized vehicle in restricted zone area during daytime",
            "Reckless driving and dangerous overtaking on busy road",
            "Vehicle without proper registration plates visible clearly",
            "Driver fled from traffic police checking point at signal",
            "Commercial vehicle in residential area during restricted hours",
            "Illegal parking in disabled person spot at shopping mall",

            "Riding motorcycle without helmet protection gear on highway", # No Helmet 2
            "Exceeding the speed limit on a state highway", # Over Speeding 2
            "Ran a red light at a busy intersection", # Signal Jumping 2
            "Four people on a two-wheeler is a triple riding offense", # Triple Riding 2
            "Texting while driving is dangerous and illegal", # Mobile Phone Use 2
            "Truck left unattended in a designated no parking area", # No Parking 2
            "Driving against the flow of traffic on a divided road", # Wrong Side Driving 2
            "Suspected drunk driver pulled over by police patrol", # Drunk Driving 2
            "Vehicle had no proof of current insurance policy", # No Insurance 2
            "Vehicle failed the mandatory emissions test", # Pollution Violation 2
            "Overloaded commercial vehicle on a city street", # Overloading 2
            "Driver could not produce a valid driver's license", # No License 2
            "Neither driver nor passenger was wearing a seatbelt", # Seat Belt Violation 2
            "Vehicle had illegally dark window tinting", # Vehicle Modification 2
            "Commercial truck in a restricted delivery time zone", # Zone Violation 2
            "Driving erratically and weaving through traffic", # Reckless Driving 2
            "License plates were dirty and unreadable", # Registration Issue 2
            "Fled from a traffic stop conducted by police", # Fleeing Police 2
            "Operating a commercial vehicle in a residential area late at night", # Commercial Violation 2
            "Parking illegally in a handicapped accessible space", # Illegal Parking 2

            "Caught riding without a helmet", # No Helmet 3
            "Caught speeding on the freeway", # Over Speeding 3
            "Went through a red light", # Signal Jumping 3
            "Too many people on a bike", # Triple Riding 3
            "On the phone while driving", # Mobile Phone Use 3
            "Parked where signs say no parking", # No Parking 3
            "Driving the wrong way down the street", # Wrong Side Driving 3
            "Pulled over for suspected DUI", # Drunk Driving 3
            "No insurance papers in the car", # No Insurance 3
            "Car failed smog check", # Pollution Violation 3
            "Truck had too much weight", # Overloading 3
            "Didn't have a valid license", # No License 3
            "Both front passengers unbuckled", # Seat Belt Violation 3
            "Car had illegal modifications", # Vehicle Modification 3
            "Entered a restricted access zone", # Zone Violation 3
            "Driving dangerously fast", # Reckless Driving 3
            "License plate wasn't visible", # Registration Issue 3
            "Drove off when police tried to stop them", # Fleeing Police 3
            "Commercial vehicle in a no-commercial zone", # Commercial Violation 3
            "Parked in a spot reserved for disabled", # Illegal Parking 3

            "Motorcycle rider without a helmet on city road", # No Helmet 4
            "Car speeding on highway over limit", # Over Speeding 4
            "Driver jumping red signal at traffic light", # Signal Jumping 4
            "Three people riding on scooter dangerously", # Triple Riding 4
            "Person using mobile phone while driving car", # Mobile Phone Use 4
            "Commercial truck driving in residential zone", # Commercial Violation 4
            "Driving under influence of alcohol near police station", # Drunk Driving 4
            "Escaping from police during traffic check", # Fleeing Police 4
            "Parking in a disabled parking spot", # Illegal Parking 4
            "Expired vehicle insurance policy", # No Insurance 4
            "Operating a vehicle without a valid license", # No License 4
            "Leaving vehicle in a no parking area", # No Parking 4
            "Truck carrying excessive load", # Overloading 4
            "Vehicle failing emission test", # Pollution Violation 4
            "Reckless driving maneuvers on the main road", # Reckless Driving 4
            "Vehicle with obscured license plate", # Registration Issue 4
            "Driver and passenger not wearing seatbelts", # Seat Belt Violation 4
            "Vehicle with illegal exhaust system", # Vehicle Modification 4
            "Driving against traffic on a busy street", # Wrong Side Driving 4
            "Entering a restricted zone without permission", # Zone Violation 4

             "No helmet on motorcycle", # No Helmet 5
            "Speeding in residential area", # Over Speeding 5
            "Ignoring red traffic light", # Signal Jumping 5
            "More than two people on a bike", # Triple Riding 5
            "Talking on phone while driving", # Mobile Phone Use 5
            "Parking in prohibited area", # No Parking 5
            "Wrong side driving on highway", # Wrong Side Driving 5
            "Drunk driving arrest", # Drunk Driving 5
            "No valid insurance proof", # No Insurance 5
            "Pollution test failed", # Pollution Violation 5
            "Truck overloaded", # Overloading 5
            "Driving without a license", # No License 5
            "No seatbelt worn", # Seat Belt Violation 5
            "Illegal car modification", # Vehicle Modification 5
            "Driving in restricted zone", # Zone Violation 5
            "Dangerous driving", # Reckless Driving 5
            "Unreadable license plate", # Registration Issue 5
            "Fleeing from police", # Fleeing Police 5
            "Commercial vehicle in residential area", # Commercial Violation 5
            "Illegally parked in disabled spot", # Illegal Parking 5

            "Motorcycle without helmet detected", # No Helmet 6
            "Caught speeding on camera", # Over Speeding 6
            "Ran a red light and caused accident", # Signal Jumping 6
            "Triple riding on a scooter with child", # Triple Riding 6
            "Driver distracted by phone while driving", # Mobile Phone Use 6
            "Parked in a tow away zone", # No Parking 6
            "Driving on the wrong side of the dual carriageway", # Wrong Side Driving 6
            "Failed breathalyzer test for drunk driving", # Drunk Driving 6
            "No insurance sticker displayed on vehicle", # No Insurance 6
            "Vehicle failed its annual emission test", # Pollution Violation 6
            "Overloaded truck causing damage to road", # Overloading 6
            "Driving with an expired license", # No License 6
            "Both front occupants not wearing seatbelts", # Seat Belt Violation 6
            "Modified exhaust pipe causing excessive noise", # Vehicle Modification 6
            "Heavy vehicle entering a restricted weight zone", # Zone Violation 6
            "Reckless overtaking on blind corner", # Reckless Driving 6
            "License plate covered in mud and unreadable", # Registration Issue 6
            "Driver sped away from police checkpoint", # Fleeing Police 6
            "Commercial van parked in a residential street overnight", # Commercial Violation 6
            "Vehicle parked in a reserved disabled bay without a permit", # Illegal Parking 6

             "Helmet not worn by rider", # No Helmet 7
            "Speeding violation on motorway", # Over Speeding 7
            "Failed to stop at an amber light", # Signal Jumping 7
            "More than the permitted number of passengers on motorcycle", # Triple Riding 7
            "Observed using mobile phone while driving", # Mobile Phone Use 7
            "Parked illegally on double yellow lines", # No Parking 7
            "Driving against traffic on a slip road", # Wrong Side Driving 7
            "Arrested for driving under the influence", # Drunk Driving 7
            "No valid insurance certificate presented", # No Insurance 7
            "Vehicle failed smog test", # Pollution Violation 7
            "Truck exceeding maximum permissible weight", # Overloading 7
            "Driving without proper license", # No License 7
            "Front passenger not wearing seatbelt", # Seat Belt Violation 7
            "Illegal window tinting on car", # Vehicle Modification 7
            "Entering a pedestrianized zone in a vehicle", # Zone Violation 7
            "Swerving dangerously between lanes", # Reckless Driving 7
            "Missing front license plate", # Registration Issue 7
            "Attempted to evade police pursuit", # Fleeing Police 7
            "Large vehicle parked in a residential parking area", # Commercial Violation 7
            "Parking in a disabled spot without badge", # Illegal Parking 7

            # Adding more examples to ensure sufficient data for stratified split (aiming for at least 4 per class)
            "Motorcycle rider without a helmet during traffic stop", # No Helmet 8
            "Car exceeding speed limit in a school zone", # Over Speeding 8
            "Driver ran a red light and caused a minor accident", # Signal Jumping 8
            "Three people riding on a small moped unsafely", # Triple Riding 8
            "Person seen holding and using a mobile phone while driving", # Mobile Phone Use 8
            "Truck parked in a designated bus stop area", # No Parking 8
            "Driving on the wrong side of a divided highway", # Wrong Side Driving 8
            "Pulled over for suspected drunk driving, failed field sobriety test", # Drunk Driving 8
            "Vehicle insurance policy expired last month, no valid proof", # No Insurance 8
            "Car failed the annual vehicle emissions inspection", # Pollution Violation 8
            "Heavy truck carrying materials over the weight limit", # Overloading 8
            "Driver's license was suspended due to previous violations", # No License 8
            "Both driver and front passenger were not wearing seatbelts", # Seat Belt Violation 8
            "Vehicle had an illegally loud exhaust system modification", # Vehicle Modification 8
            "Entered a pedestrian-only zone in a vehicle during restricted hours", # Zone Violation 8
            "Driving aggressively, changing lanes without signaling", # Reckless Driving 8
            "License plate is obscured by dirt and unreadable", # Registration Issue 8
            "Driver attempted to flee from police during a traffic stop", # Fleeing Police 8
            "Commercial vehicle parked in a residential neighborhood overnight", # Commercial Violation 8
            "Illegally parked in a handicapped parking spot without a valid permit", # Illegal Parking 8

            "No helmet observed on motorcycle rider", # No Helmet 9
            "Caught speeding by speed camera on highway", # Over Speeding 9
            "Red light violation at intersection caught on camera", # Signal Jumping 9
            "Triple riding on a two-wheeler with an infant", # Triple Riding 9
            "Using a mobile phone while driving through a busy area", # Mobile Phone Use 9
            "Vehicle parked in a fire lane, causing obstruction", # No Parking 9
            "Driving the wrong way on a one-way street, creating danger", # Wrong Side Driving 9
            "Drunk driving arrest after failing a breathalyzer test", # Drunk Driving 9
            "No valid vehicle insurance found during a traffic check", # No Insurance 9
            "Vehicle failed its pollution control test, emitting black smoke", # Pollution Violation 9
            "Truck overloaded with construction debris, spilling onto the road", # Overloading 9
            "Driving a vehicle without a proper driver's license", # No License 9
            "Front seat passenger not wearing a seatbelt during transit", # Seat Belt Violation 9
            "Illegal window tinting on the car is too dark", # Vehicle Modification 9
            "Entering a restricted zone without authorization during prohibited times", # Zone Violation 9
            "Driving recklessly, swerving between lanes at high speed", # Reckless Driving 9
            "Missing front license plate on the vehicle", # Registration Issue 9
            "Driver sped away from police officers at a checkpoint", # Fleeing Police 9
            "Large commercial vehicle parked in a residential street, violating regulations", # Commercial Violation 9
            "Parking illegally in a disabled person's parking spot at the store", # Illegal Parking 9

            "Motorcycle rider without helmet observed by patrol", # No Helmet 10
            "Exceeding the speed limit in a residential area", # Over Speeding 10
            "Ran a red light at a busy junction", # Signal Jumping 10
            "More than two people on a motorcycle observed", # Triple Riding 10
            "Driver using a mobile phone while driving, distracted behavior", # Mobile Phone Use 10
            "Vehicle parked in a no parking zone near a school", # No Parking 10
            "Driving on the wrong side of the road, causing a hazard", # Wrong Side Driving 10
            "Drunk driving arrest after a traffic stop and sobriety test", # Drunk Driving 10
            "No valid insurance for the vehicle presented", # No Insurance 10
            "Pollution control certificate for the car has expired", # Pollution Violation 10
            "Overloaded vehicle stopped and impounded by authorities", # Overloading 10
            "Driving without a license detected during a routine check", # No License 10
            "Seatbelt violation by both driver and front seat passenger", # Seat Belt Violation 10
            "Illegal vehicle modifications found during a roadside inspection", # Vehicle Modification 10
            "Restricted zone entry violation by an unauthorized vehicle", # Zone Violation 10
            "Reckless driving caught on camera, resulting in a fine", # Reckless Driving 10
            "Obscured rear license plate detected by police", # Registration Issue 10
            "Fleeing from police pursuit after committing a traffic offense", # Fleeing Police 10
            "Commercial vehicle restriction violation in a residential area during prohibited hours", # Commercial Violation 10
            "Parking in a disabled parking area illegally without the proper permit displayed", # Illegal Parking 10

            # Adding more examples to further increase dataset size and ensure enough for stratified split
            "Lack of helmet usage by motorcycle operator", # No Helmet 11
            "Speeding violation recorded by radar gun", # Over Speeding 11
            "Failure to obey red traffic signal", # Signal Jumping 11
            "More than two persons on a single motorcycle", # Triple Riding 11
            "Operating vehicle while using cell phone", # Mobile Phone Use 11
            "Vehicle left in prohibited parking zone", # No Parking 11
            "Driving in the opposite direction of traffic", # Wrong Side Driving 11
            "Arrest for driving under the influence of alcohol", # Drunk Driving 11
            "Vehicle insurance not current or valid", # No Insurance 11
            "Vehicle failed state emissions test", # Pollution Violation 11
            "Heavy truck exceeding weight limits", # Overloading 11
            "Driving without a valid driver's license", # No License 11
            "Driver and front passenger not wearing seat restraints", # Seat Belt Violation 11
            "Illegal exhaust system modification on car", # Vehicle Modification 11
            "Entry into restricted zone without authorization", # Zone Violation 11
            "Driving in a dangerous and erratic manner", # Reckless Driving 11
            "License plate obscured or not visible", # Registration Issue 11
            "Attempting to evade police traffic stop", # Fleeing Police 11
            "Commercial vehicle parked in residential neighborhood overnight", # Commercial Violation 11
            "Illegally parked in a designated handicapped spot", # Illegal Parking 11

            "Motorcycle rider observed without protective helmet", # No Helmet 12
            "Caught exceeding the speed limit on city street", # Over Speeding 12
            "Disregarding red traffic light at intersection", # Signal Jumping 12
            "Three passengers on a motorcycle", # Triple Riding 12
            "Using a mobile phone while driving a car", # Mobile Phone Use 12
            "Vehicle parked in a tow-away zone", # No Parking 12
            "Driving the wrong way on a divided highway", # Wrong Side Driving 12
            "Drunk driving arrest after roadside test", # Drunk Driving 12
            "No valid insurance for the vehicle", # No Insurance 12
            "Vehicle failed annual pollution inspection", # Pollution Violation 12
            "Truck overloaded with construction materials", # Overloading 12
            "Driving with an expired driver's license", # No License 12
            "Both front occupants not wearing seatbelts", # Seat Belt Violation 12
            "Illegal window tinting on vehicle", # Vehicle Modification 12
            "Vehicle entered a restricted vehicle zone", # Zone Violation 12
            "Reckless driving resulting in near collision", # Reckless Driving 12
            "License plate is missing or unreadable", # Registration Issue 12
            "Driver fled from traffic police", # Fleeing Police 12
            "Commercial vehicle parked in residential area during prohibited times", # Commercial Violation 12
            "Parking in a disabled parking spot without a permit", # Illegal Parking 12

            "No helmet on head while riding motorcycle", # No Helmet 13
            "Exceeding speed limit on suburban road", # Over Speeding 13
            "Running a red light camera ticket issued", # Signal Jumping 13
            "More than allowed passengers on motorcycle", # Triple Riding 13
            "Driver texting while driving vehicle", # Mobile Phone Use 13
            "Vehicle parked in fire hydrant zone", # No Parking 13
            "Driving against traffic flow on city street", # Wrong Side Driving 13
            "Caught drunk driving after police stop", # Drunk Driving 13
            "No insurance policy found for car", # No Insurance 13
            "Car failed smog test emissions too high", # Pollution Violation 13
            "Truck overloaded with gravel", # Overloading 13
            "Driving car without valid license", # No License 13
            "Front seat passenger unbelted", # Seat Belt Violation 13
            "Illegal car exhaust modification", # Vehicle Modification 13
            "Driving in pedestrian zone during restricted hours", # Zone Violation 13
            "Reckless driving near school zone", # Reckless Driving 13
            "License plate missing from vehicle rear", # Registration Issue 13
            "Fleeing from police officers on foot", # Fleeing Police 13
            "Commercial vehicle parked in residential driveway", # Commercial Violation 13
            "Parking in handicapped spot no permit", # Illegal Parking 13

            "Motorcycle rider no helmet observed by officer", # No Helmet 14
            "Speeding on residential street complaints received", # Over Speeding 14
            "Ran red light at intersection caused delay", # Signal Jumping 14
            "Triple riding on moped unsafe", # Triple Riding 14
            "Person on mobile phone while driving observed", # Mobile Phone Use 14
            "Parked illegally double yellow lines", # No Parking 14
            "Driving wrong direction on freeway entrance", # Wrong Side Driving 14
            "Drunk driving arrest after collision", # Drunk Driving 14
            "No insurance proof in car during check", # No Insurance 14
            "Vehicle failed emissions test black smoke", # Pollution Violation 14
            "Overloaded truck spilling contents on road", # Overloading 14
            "Driving with expired license detected", # No License 14
            "Driver and passenger not wearing seat belts", # Seat Belt Violation 14
            "Illegal window tinting too dark on front windows", # Vehicle Modification 14
            "Entering restricted zone without permission signage ignored", # Zone Violation 14
            "Reckless driving swerving between lanes at high speed", # Reckless Driving 14
            "Obscured front license plate on vehicle", # Registration Issue 14
            "Attempting to evade police high speed chase", # Fleeing Police 14
            "Commercial vehicle in residential area during night hours complaints", # Commercial Violation 14
            "Parking in disabled spot no valid placard displayed", # Illegal Parking 14

            # Adding more examples to ensure sufficient data for stratified split (aiming for at least 5 per class)
            "Wearing no helmet while operating motorcycle", # No Helmet 15
            "Speeding over the limit on a city street", # Over Speeding 15
            "Ignoring a red signal at a crossroads", # Signal Jumping 15
            "More than two individuals on a motorcycle", # Triple Riding 15
            "Driver using a mobile phone while driving", # Mobile Phone Use 15
            "Vehicle left in a forbidden parking area", # No Parking 15
            "Driving the incorrect way on a divided road", # Wrong Side Driving 15
            "Arrested for driving while intoxicated", # Drunk Driving 15
            "Vehicle without current insurance papers", # No Insurance 15
            "Vehicle failed the emissions test", # Pollution Violation 15
            "Heavy duty truck exceeding weight limit", # Overloading 15
            "Operating a vehicle without a proper license", # No License 15
            "Both front occupants not wearing seatbelts", # Seat Belt Violation 15
            "Unlawful modification of vehicle exhaust", # Vehicle Modification 15
            "Entering a restricted zone without authority", # Zone Violation 15
            "Dangerous driving conduct observed", # Reckless Driving 15
            "Vehicle license plate is not visible", # Registration Issue 15
            "Attempting to avoid police traffic stop", # Fleeing Police 15
            "Commercial vehicle parked in residential zone overnight", # Commercial Violation 15
            "Parking in a reserved disabled space without permit", # Illegal Parking 15

            # Adding more examples to ensure sufficient data for stratified split (aiming for at least 5 per class)
            "Wearing no helmet while operating motorcycle", # No Helmet 16
            "Speeding over the limit on a city street", # Over Speeding 16
            "Ignoring a red signal at a crossroads", # Signal Jumping 16
            "More than two individuals on a motorcycle", # Triple Riding 16
            "Driver using a mobile phone while driving", # Mobile Phone Use 16
            "Vehicle left in a forbidden parking area", # No Parking 16
            "Driving the incorrect way on a divided road", # Wrong Side Driving 16
            "Arrested for driving while intoxicated", # Drunk Driving 16
            "Vehicle without current insurance papers", # No Insurance 16
            "Vehicle failed the emissions test", # Pollution Violation 16
            "Heavy duty truck exceeding weight limit", # Overloading 16
            "Operating a vehicle without a proper license", # No License 16
            "Both front occupants not wearing seatbelts", # Seat Belt Violation 16
            "Unlawful modification of vehicle exhaust", # Vehicle Modification 16
            "Entering a restricted zone without authority", # Zone Violation 16
            "Dangerous driving conduct observed", # Reckless Driving 16
            "Vehicle license plate is not visible", # Registration Issue 16
            "Attempting to avoid police traffic stop", # Fleeing Police 16
            "Commercial vehicle parked in residential zone overnight", # Commercial Violation 16
            "Parking in a reserved disabled space without permit", # Illegal Parking 16
        ],
        'violation_type': [
            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'Commercial Violation', 'Drunk Driving', 'Fleeing Police', 'Illegal Parking', 'No Insurance',
            'No License', 'No Parking', 'Overloading', 'Pollution Violation', 'Reckless Driving',
            'Registration Issue', 'Seat Belt Violation', 'Vehicle Modification', 'Wrong Side Driving', 'Zone Violation',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

             'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

             'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

            'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

             'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

             'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',

             'No Helmet', 'Over Speeding', 'Signal Jumping', 'Triple Riding', 'Mobile Phone Use',
            'No Parking', 'Wrong Side Driving', 'Drunk Driving', 'No Insurance', 'Pollution Violation',
            'Overloading', 'No License', 'Seat Belt Violation', 'Vehicle Modification', 'Zone Violation',
            'Reckless Driving', 'Registration Issue', 'Fleeing Police', 'Commercial Violation', 'Illegal Parking',
        ]
    }

    df = pd.DataFrame(violation_data)
    return df

# Create dataset
print("📊 CREATING TRAFFIC VIOLATION DATASET...")
df = create_comprehensive_dataset()
print(f"Dataset Shape: {df.shape}")
print(f"Violation Types: {df['violation_type'].nunique()}")
print("\nDataset Sample:")
print(df.head())
print("\nClass Distribution:")
print(df['violation_type'].value_counts())


# =============================================================================
# 2. TEXT PREPROCESSING CLASS
# =============================================================================

class TextPreprocessor:
    """Advanced text preprocessing pipeline for NLP tasks"""

    def __init__(self):
        # Custom stop words for traffic domain
        self.custom_stop_words = {
            'vehicle', 'driver', 'road', 'street', 'way', 'area', 'zone',
            'traffic', 'police', 'checking', 'during', 'while', 'without', 'using'
        }

    def clean_text(self, text):
        """Step 1: Basic text cleaning"""
        # Convert to lowercase
        text = text.lower()
        # Remove special characters and digits (keep only alphabets and spaces)
        text = re.sub(r'[^a-zA-Z\s]', '', text)
        # Remove extra whitespace
        text = ' '.join(text.split())
        return text

    def remove_stopwords(self, text):
        """Remove custom stopwords"""
        words = text.split()
        filtered_words = [word for word in words if word not in self.custom_stop_words]
        return ' '.join(filtered_words)

    def full_preprocessing_pipeline(self, text):
        """Complete text preprocessing pipeline"""
        # Clean text
        text = self.clean_text(text)
        # Remove stopwords
        text = self.remove_stopwords(text)
        return text

# Initialize preprocessor
print("\n🔧 INITIALIZING TEXT PREPROCESSOR...")
preprocessor = TextPreprocessor()

# Apply preprocessing to dataset
print("🔄 APPLYING TEXT PREPROCESSING...")
df['processed_text'] = df['text'].apply(preprocessor.full_preprocessing_pipeline)

print("Preprocessing Examples:")
for i in range(3):
    print(f"Original: {df['text'].iloc[i][:60]}...")
    print(f"Processed: {df['processed_text'].iloc[i][:60]}...")
    print("-" * 80)

# =============================================================================
# 3. FEATURE EXTRACTION TECHNIQUES
# =============================================================================

print("\n🎯 FEATURE EXTRACTION TECHNIQUES")
print("=" * 50)

# Prepare data for modeling
texts = df['processed_text'].tolist()
labels = df['violation_type'].tolist()

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(labels)

print(f"Number of classes: {len(label_encoder.classes_)}")
print(f"Classes: {list(label_encoder.classes_)}")

# 3.1 Bag-of-Words Model
print("\n📊 3.1 BAG-OF-WORDS MODEL")
bow_vectorizer = CountVectorizer(
    max_features=50,
    ngram_range=(1, 2)  # Unigrams and bigrams
)
X_bow = bow_vectorizer.fit_transform(texts)
print(f"BOW Matrix Shape: {X_bow.shape}")
print(f"BOW Features (sample): {list(bow_vectorizer.get_feature_names_out())[:10]}")

# 3.2 TF-IDF Model
print("\n📊 3.2 TF-IDF MODEL")
tfidf_vectorizer = TfidfVectorizer(
    max_features=50,
    ngram_range=(1, 2)
)
X_tfidf = tfidf_vectorizer.fit_transform(texts)
print(f"TF-IDF Matrix Shape: {X_tfidf.shape}")
print(f"TF-IDF Features (sample): {list(tfidf_vectorizer.get_feature_names_out())[:10]}")

# =============================================================================
# 4. LOGISTIC REGRESSION MODEL
# =============================================================================

print("\n📈 4. LOGISTIC REGRESSION CLASSIFICATION")
print("=" * 50)

# Split data
X_train_bow, X_test_bow, y_train, y_test = train_test_split(
    X_bow, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded
)

X_train_tfidf, X_test_tfidf, _, _ = train_test_split(
    X_tfidf, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded
)

# Train Logistic Regression models
lr_model_bow = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)
lr_model_bow.fit(X_train_bow, y_train)

lr_model_tfidf = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)
lr_model_tfidf.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_bow = lr_model_bow.predict(X_test_bow)
y_pred_tfidf = lr_model_tfidf.predict(X_test_tfidf)

print("Logistic Regression Results:")
print(f"BOW Accuracy: {accuracy_score(y_test, y_pred_bow):.4f}")
print(f"TF-IDF Accuracy: {accuracy_score(y_test, y_pred_tfidf):.4f}")

# =============================================================================
# 5. MODEL EVALUATION AND VISUALIZATION
# =============================================================================

print("\n📊 5. MODEL EVALUATION AND VISUALIZATION")
print("=" * 50)

class ModelEvaluator:
    """Comprehensive model evaluation and visualization"""

    def __init__(self):
        pass # Label encoder will be passed during method calls

    def generate_classification_report(self, y_true, y_pred, model_name, target_names):
        """Generate detailed classification report"""
        print(f"\n{model_name} Classification Report:")
        print("-" * 50)
        print(classification_report(y_true, y_pred, target_names=target_names))

    def plot_confusion_matrix(self, y_true, y_pred, model_name, target_names):
        """Plot confusion matrix"""
        cm = confusion_matrix(y_true, y_pred)

        plt.figure(figsize=(10, 8)) # Increased figure size
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                   xticklabels=target_names,
                   yticklabels=target_names)
        plt.title(f'Confusion Matrix - {model_name}')
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.xticks(rotation=45, ha='right') # Rotated x-axis labels
        plt.yticks(rotation=0)
        plt.tight_layout()
        plt.show()

# Initialize evaluator
evaluator = ModelEvaluator()

# Generate reports
evaluator.generate_classification_report(y_test, y_pred_bow, "Logistic Regression (BOW)", label_encoder.classes_)
evaluator.plot_confusion_matrix(y_test, y_pred_bow, "Logistic Regression (BOW)", label_encoder.classes_)

# =============================================================================
# 6. FEATURE IMPORTANCE ANALYSIS
# =============================================================================

print("\n🔍 6. FEATURE IMPORTANCE ANALYSIS")
print("=" * 50)

def analyze_feature_importance(model, vectorizer, label_encoder, top_n=10):
    """Analyze feature importance for linear models"""
    if hasattr(model, 'coef_'):
        feature_names = vectorizer.get_feature_names_out()

        print("Top Features by Class:")
        print("-" * 40)

        for i, class_name in enumerate(label_encoder.classes_):
            coef = model.coef_[i]
            top_indices = coef.argsort()[-top_n:][::-1]

            print(f"\n{class_name}:")
            for idx in top_indices:
                print(f"  {feature_names[idx]}: {coef[idx]:.4f}")

# Analyze feature importance
analyze_feature_importance(lr_model_bow, bow_vectorizer, label_encoder)

# =============================================================================
# 7. PREDICTION ON NEW DATA
# =============================================================================

print("\n🔮 7. PREDICTION ON NEW DATA")
print("=" * 50)

def predict_violation_type(text, preprocessor, vectorizer, model, label_encoder):
    """Predict violation type for new text"""
    # Preprocess text
    processed_text = preprocessor.full_preprocessing_pipeline(text)

    # Transform using vectorizer
    text_vectorized = vectorizer.transform([processed_text])

    # Predict
    prediction = model.predict(text_vectorized)
    probability = model.predict_proba(text_vectorized)

    # Get results
    predicted_class = label_encoder.inverse_transform(prediction)[0]
    confidence = np.max(probability)

    return predicted_class, confidence, processed_text

# Test predictions
test_cases = [
    "motorcycle rider without helmet on city road",
    "car speeding on highway over limit",
    "driver jumping red signal at traffic light",
    "three people riding on scooter dangerously",
    "person using mobile phone while driving car"
]

print("Prediction Examples:")
print("-" * 80)
for i, test_case in enumerate(test_cases):
    predicted_class, confidence, processed_text = predict_violation_type(
        test_case, preprocessor, bow_vectorizer, lr_model_bow, label_encoder
    )
    print(f"Test Case {i+1}:")
    print(f"  Input: {test_case}")
    print(f"  Predicted: {predicted_class}")
    print(f"  Confidence: {confidence:.4f}")
    print("-" * 80)

# =============================================================================
# 8. COMPREHENSIVE SUMMARY
# =============================================================================

print("\n🎯 8. COMPREHENSIVE SUMMARY")
print("=" * 50)

print("NLP TECHNIQUES IMPLEMENTED:")
techniques = [
    "✓ Text Preprocessing and Cleaning",
    "✓ Tokenization (via CountVectorizer)",
    "✓ Stop Words Removal",
    "✓ Text Normalization",
    "✓ Bag-of-Words (BoW) Model",
    "✓ TF-IDF Technique",
    "✓ Logistic Regression",
    "✓ Model Evaluation and Interpretation",
    "✓ Feature Importance Analysis",
    "✓ Prediction Pipeline"
]

for technique in techniques:
    print(f"  {technique}")

print(f"\nDATASET STATISTICS:")
print(f"  Total samples: {len(df)}")
print(f"  Violation types: {len(df['violation_type'].unique())}")
print(f"  Feature dimensions - BOW: {X_bow.shape[1]}, TF-IDF: {X_tfidf.shape[1]}")

print(f"\nMODEL PERFORMANCE:")
print(f"  Logistic Regression (BOW): {accuracy_score(y_test, y_pred_bow):.4f}")
print(f"  Logistic Regression (TF-IDF): {accuracy_score(y_test, y_pred_tfidf):.4f}")

# =============================================================================
# 9. ADDITIONAL VISUALIZATIONS
# =============================================================================

print("\n📈 9. ADDITIONAL VISUALIZATIONS")
print("=" * 50)

# Plot class distribution
plt.figure(figsize=(12, 7)) # Increased figure size
class_distribution = df['violation_type'].value_counts()
plt.bar(class_distribution.index, class_distribution.values)
plt.title('Violation Type Distribution')
plt.xlabel('Violation Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Compare model performance
models = ['LogReg (BOW)', 'LogReg (TF-IDF)']
accuracies = [accuracy_score(y_test, y_pred_bow), accuracy_score(y_test, y_pred_tfidf)]

plt.figure(figsize=(8, 6))
plt.bar(models, accuracies, color=['skyblue', 'lightcoral'])
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
for i, v in enumerate(accuracies):
    plt.text(i, v + 0.01, f'{v:.4f}', ha='center', va='bottom')
plt.tight_layout()
plt.show()

# =============================================================================
# 10. SAVE PROCESSED DATA AND MODEL INFO
# =============================================================================

print("\n💾 10. SAVING PROCESSED DATA")
print("=" * 50)

# Save processed dataset
df.to_csv('traffic_violations_processed.csv', index=False)
print("✓ Processed dataset saved as 'traffic_violations_processed.csv'")

# Display final dataset info
print("\n📋 FINAL PROCESSED DATASET:")
print(df[['violation_type', 'processed_text']].head())

print("\n" + "=" * 70)
print("✅ NLP PIPELINE COMPLETED SUCCESSFULLY!")
print("=" * 70)

print(f"""
🎉 SUMMARY OF IMPLEMENTED TECHNIQUES:

1.  TEXT PREPROCESSING:
    - Lowercasing
    - Special character removal
    - Whitespace normalization
    - Custom stopword removal

2.  TOKENIZATION:
    - Automated through CountVectorizer
    - N-gram support (unigrams + bigrams)

3.  FEATURE EXTRACTION:
    - Bag-of-Words (BoW) Model
    - TF-IDF (TfidfVectorizer)

4.  MODEL TRAINING:
    - Logistic Regression (Multinomial)
    - Two feature types (BOW & TF-IDF)

5.  MODEL EVALUATION:
    - Accuracy scores
    - Classification reports
    - Confusion matrices
    - Feature importance analysis

6.  PREDICTION PIPELINE:
    - End-to-end prediction system
    - Confidence scoring

Dataset: {len(df)} traffic violation records
Best Model Accuracy: {max(accuracies):.4f}
Ready for production use!
""")